import csv, sqlite3

reader = csv.reader(open("ks_compound.txt","r"),delimiter="\t")
reader.next()

con = sqlite3.connect("ks_comp.db")
cur = con.cursor()
con.execute("CREATE TABLE kinase_sarfali(COMPOUND_ID primary key
	,EXTERNAL_SOURCES
	,SYNONYMS,MOLWEIGHT
	,ALOGP,HYDROGEN_BOND_ACCEPTORS
	,HYDROGEN_BOND_DONORS,POLAR_SURFACE_AREA
	,NUM_RO5_VIOLATIONS
	,MED_CHEM_FRIENDLY
	,SMILES)")

for COMPOUND_ID,EXTERNAL_SOURCES,SYNONYMS,MOLWEIGHT,ALOGP,HYDROGEN_BOND_ACCEPTORS,HYDROGEN_BOND_DONORS,POLAR_SURFACE_AREA,NUM_RO5_VIOLATIONS,MED_CHEM_FRIENDLY,SMILES in reader:
	cur.execute("INSERT INTO kinase_sarfali(COMPOUND_ID,EXTERNAL_SOURCES,SYNONYMS,MOLWEIGHT,ALOGP,HYDROGEN_BOND_ACCEPTORS,HYDROGEN_BOND_DONORS,POLAR_SURFACE_AREA,NUM_RO5_VIOLATIONS,MED_CHEM_FRIENDLY,SMILES) VALUES(?,?,?,?,?,?,?,?,?,?,?)",(COMPOUND_ID,EXTERNAL_SOURCES,SYNONYMS,MOLWEIGHT,ALOGP,HYDROGEN_BOND_ACCEPTORS,HYDROGEN_BOND_DONORS,POLAR_SURFACE_AREA,NUM_RO5_VIOLATIONS,MED_CHEM_FRIENDLY,SMILES))
	
con.commit()
con.close()

